module.exports = {
    Player: require("./Player"),
    TestDataSource: require("./TestDataSource"),
    EndTitlesGeneratorDataSource: require("./EndTitlesGeneratorDataSource"),
    Utils: require("./Utils"),
    ConsoleDataOutput: require("./ConsoleDataOutput"),
    DiscordMessageDataOutput: require("./DiscordMessageDataOutput"),
    GifDataSource: require("./GifDataSource"),
    AsciimationCoNzDataSource: require("./AsciimationCoNzDataSource"),
    AsciiCoUkDataSource: require("./AsciiCoUkDataSource"),
    AsciinemaDataSource: require("./AsciinemaDataSource"),
    PngDataSource: require("./PngDataSource"),
    ResizeDataSource: require("./ResizeDataSource"),
    AsciiLiveDataSource: require("./AsciiLiveDataSource"),
};